/**
 * Ticket Issue 생성.
 *
 * Ticket 레코드를 GitHub Issue로 변환. 워커가 픽업해서 처리.
 *
 * Issue 본문 형식이 워커 처리의 결정론성을 좌우하므로 표준 템플릿 엄격 준수.
 */

import type { Project, Ticket } from '@buildee/db';
import { getOctokit } from '../lib/github-app.js';
import { config } from '../lib/config.js';
import { appPrisma, projectShortId } from '@buildee/db';
import { logger } from '../lib/logger.js';

export async function createIssueForTicket(
  ticket: Ticket,
  project: Project,
): Promise<{ issueNumber: number; issueUrl: string }> {
  const octokit = await getOctokit();
  const repoName = `proj-${projectShortId(project.id)}`;

  const title = renderTitle(ticket);
  const body = renderBody(ticket, project);
  const labels = ['claude-process', `category:${ticket.type.toLowerCase()}`];

  const { data: issue } = await octokit.rest.issues.create({
    owner: config.GITHUB_ORG,
    repo: repoName,
    title,
    body,
    labels,
  });

  // Ticket 레코드 업데이트
  await appPrisma().ticket.update({
    where: { id: ticket.id },
    data: { githubIssueNumber: issue.number },
  });

  logger.info(
    { ticketId: ticket.id, issueNumber: issue.number, repo: repoName },
    'GitHub issue created for ticket',
  );

  return { issueNumber: issue.number, issueUrl: issue.html_url };
}

function renderTitle(ticket: Ticket): string {
  const spec = ticket.spec as { intent?: string };
  const intent = spec.intent ?? '(no intent)';
  // 80자 제한
  const truncated = intent.length > 70 ? intent.slice(0, 67) + '...' : intent;
  return `[${ticket.type}] ${truncated}`;
}

function renderBody(ticket: Ticket, project: Project): string {
  const spec = ticket.spec as {
    intent?: string;
    category?: string;
    proposedChanges?: any;
    affectedLayers?: string[];
  };

  return `<!-- buildee:ticket:${ticket.id} -->

## Goal

${spec.intent ?? '(no intent)'}

## Context

- **Ticket ID**: \`${ticket.id}\`
- **Type**: \`${ticket.type}\`
- **Category**: \`${spec.category ?? 'unknown'}\`
- **Affected layers**: ${(spec.affectedLayers ?? []).map((l) => `\`${l}\``).join(', ') || 'none'}

## Proposed changes

\`\`\`json
${JSON.stringify(spec.proposedChanges ?? {}, null, 2)}
\`\`\`

## Acceptance criteria

- [ ] Changes implement the goal as described
- [ ] All guardrails pass (build, lint, domain rules)
- [ ] Traceability comments present in changed files
- [ ] No design tokens or dependencies violations
- [ ] PR description summarizes what changed and why

## Workflow

1. Add \`[STATUS:STARTED]\` comment confirming you've read the spec
2. Implement changes on a branch \`ticket-${ticket.id.slice(0, 8)}-...\`
3. Add \`[STATUS:WORKING]\` comments for major milestones
4. Run \`npm run build\` + linters before opening PR
5. Open PR with \`Closes #<this-issue>\`
6. Add \`[STATUS:READY_FOR_REVIEW]\` comment when PR is ready

If the spec is ambiguous, post \`[STATUS:CLARIFICATION_NEEDED]\` and stop.

---

<sub>This issue was auto-generated by Buildee server. Project: ${project.name}.
Reference: \`CLAUDE.md\` for project-specific rules.</sub>
`;
}
